
package haniffa.catering.Admin.Dashboard;

import haniffa.catering.Admin.Classes.BeefBiriyani;
import haniffa.catering.Admin.Classes.ChickenBiriyani;
import haniffa.catering.Admin.Classes.ExtraChicken;
import haniffa.catering.Admin.Classes.ExtraWattalapam;
import haniffa.catering.Admin.Classes.MuttonBiriyani;
import haniffa.catering.Admin.Classes.Order;
import javax.swing.JLabel;

/**
 *
 * @author HP
 */
public class CreateOrder extends javax.swing.JFrame {

    /**
     * Creates new form CreateOrder
     */
    public CreateOrder() {
        initComponents();
        Order.displayAmount(chickenBiriyaniUP, beefBiriyaniUP, muttonBiriyaniUP, extraChickenUP, extraWattalapamUP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chickenBiriyaniQty = new javax.swing.JSpinner();
        beefBiriyaniQty = new javax.swing.JSpinner();
        muttonBiriyaniQty = new javax.swing.JSpinner();
        extraChickenQty = new javax.swing.JSpinner();
        extraWattalapamQty = new javax.swing.JSpinner();
        chickenBiriyaniUP = new javax.swing.JLabel();
        beefBiriyaniUP = new javax.swing.JLabel();
        muttonBiriyaniUP = new javax.swing.JLabel();
        extraChickenUP = new javax.swing.JLabel();
        extraWattalapamUP = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        amoutTotal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pendingBalance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chickenBiriyaniAmount = new javax.swing.JLabel();
        beefBiriyaniAmount = new javax.swing.JLabel();
        muttonBiriyaniAmount = new javax.swing.JLabel();
        extraChickenAmount = new javax.swing.JLabel();
        extraWattalapamAmount = new javax.swing.JLabel();
        txtAdvancePayment = new javax.swing.JTextField();
        btnDashboard = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Customer Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 6, -1, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 56, 154, -1));
        jPanel2.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 112, 154, -1));

        jLabel2.setText("Phone Number");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 90, -1, -1));

        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 34, 37, -1));

        jLabel4.setText("Chicken Biriyani");

        jLabel5.setText("Beef Biriyani");

        jLabel6.setText("Mutton Biriyani");

        jLabel7.setText("Extra Chicken");

        jLabel8.setText("Extra Watalapam");

        chickenBiriyaniQty.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                chickenBiriyaniQtyAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        chickenBiriyaniQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chickenBiriyaniQtyStateChanged(evt);
            }
        });

        beefBiriyaniQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                beefBiriyaniQtyStateChanged(evt);
            }
        });

        muttonBiriyaniQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                muttonBiriyaniQtyStateChanged(evt);
            }
        });

        extraChickenQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                extraChickenQtyStateChanged(evt);
            }
        });

        extraWattalapamQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                extraWattalapamQtyStateChanged(evt);
            }
        });

        chickenBiriyaniUP.setText("Chicken Biriyani");

        beefBiriyaniUP.setText("Beef Biriyani");

        muttonBiriyaniUP.setText("Mutton Biriyani");

        extraChickenUP.setText("Extra Chicken");

        extraWattalapamUP.setText("Extra Watalapam");

        jLabel14.setText("Total");

        amoutTotal.setText("000.00");

        jLabel16.setText("Advance");

        pendingBalance.setText("000.00");

        jLabel18.setText("Balance");

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chickenBiriyaniAmount.setText("00");

        beefBiriyaniAmount.setText("00");

        muttonBiriyaniAmount.setText("00");

        extraChickenAmount.setText("00");

        extraWattalapamAmount.setText("00");

        txtAdvancePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvancePaymentActionPerformed(evt);
            }
        });

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chickenBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(chickenBiriyaniUP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chickenBiriyaniAmount))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beefBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(beefBiriyaniUP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beefBiriyaniAmount))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(muttonBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(muttonBiriyaniUP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(muttonBiriyaniAmount))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(extraChickenQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(extraChickenUP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(extraChickenAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(extraWattalapamQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(extraWattalapamUP)
                .addGap(18, 18, 18)
                .addComponent(extraWattalapamAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(amoutTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addGap(28, 28, 28)
                .addComponent(txtAdvancePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pendingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnDashboard)
                .addGap(154, 154, 154)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnConfirm))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chickenBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(chickenBiriyaniUP)
                            .addComponent(chickenBiriyaniAmount))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beefBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(beefBiriyaniUP)
                            .addComponent(beefBiriyaniAmount))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(muttonBiriyaniQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(muttonBiriyaniUP)
                            .addComponent(muttonBiriyaniAmount))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(extraChickenQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extraChickenUP)
                            .addComponent(extraChickenAmount))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extraWattalapamQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(extraWattalapamUP)
                            .addComponent(extraWattalapamAmount))))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(amoutTotal))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtAdvancePayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(pendingBalance))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(btnConfirm)))))
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Item Name");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Quantity");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Unit Price");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Amount");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(51, 51, 51)
                .addComponent(jLabel20)
                .addGap(26, 26, 26)
                .addComponent(jLabel21)
                .addGap(49, 49, 49)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel27))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chickenBiriyaniQtyAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_chickenBiriyaniQtyAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chickenBiriyaniQtyAncestorAdded

    private void chickenBiriyaniQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chickenBiriyaniQtyStateChanged
        // TODO add your handling code here:
        int quantity = (int) chickenBiriyaniQty.getValue();
        ChickenBiriyani chickenBiriyaniItem = new ChickenBiriyani();
        double amount = quantity * chickenBiriyaniItem.getPrice();
        chickenBiriyaniAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        Order.calculateTotal(labels);
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
        
        
        
    }//GEN-LAST:event_chickenBiriyaniQtyStateChanged

    private void beefBiriyaniQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_beefBiriyaniQtyStateChanged
        // TODO add your handling code here:
        int quantity = (int) beefBiriyaniQty.getValue();
        BeefBiriyani BeefBiriyaniItem = new BeefBiriyani();
        double amount = quantity * BeefBiriyaniItem.getPrice();
        beefBiriyaniAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        Order.calculateTotal(labels);
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
       
        
    }//GEN-LAST:event_beefBiriyaniQtyStateChanged

    private void muttonBiriyaniQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_muttonBiriyaniQtyStateChanged
        // TODO add your handling code here:
        int quantity = (int) muttonBiriyaniQty.getValue();
        MuttonBiriyani MuttonBiriyaniItem = new MuttonBiriyani();
        double amount = quantity * MuttonBiriyaniItem.getPrice();
        muttonBiriyaniAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        Order.calculateTotal(labels);
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
       
        
    }//GEN-LAST:event_muttonBiriyaniQtyStateChanged

    private void extraChickenQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_extraChickenQtyStateChanged
        // TODO add your handling code here:
          // TODO add your handling code here:
        int quantity = (int) extraChickenQty.getValue();
        ExtraChicken ExtraChickenItem = new ExtraChicken();
        double amount = quantity * ExtraChickenItem.getPrice();
        extraChickenAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        Order.calculateTotal(labels);
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
       
        
    }//GEN-LAST:event_extraChickenQtyStateChanged

    private void extraWattalapamQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_extraWattalapamQtyStateChanged
        // TODO add your handling code here:
        int quantity = (int) extraWattalapamQty.getValue();
        ExtraWattalapam ExtraWattalapamItem = new ExtraWattalapam();
        double amount = quantity * ExtraWattalapamItem.getPrice();
        extraWattalapamAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
      
        
    }//GEN-LAST:event_extraWattalapamQtyStateChanged

    private void txtAdvancePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvancePaymentActionPerformed
        // TODO add your handling code here:
        int quantity = (int) extraWattalapamQty.getValue();
        ExtraWattalapam ExtraWattalapamItem = new ExtraWattalapam();
        double amount = quantity * ExtraWattalapamItem.getPrice();
        extraWattalapamAmount.setText("$" + String.format("%2f", amount));
        JLabel[] labels = {chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount};
        double total = Order.calculateTotal(labels);
        amoutTotal.setText("$" + String.format("%2f", total));
        String advancePayment = txtAdvancePayment.getName();
        Order.balanceAmount(total, txtAdvancePayment, advancePayment, pendingBalance);
    }//GEN-LAST:event_txtAdvancePaymentActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String customerName = txtName.getText();
        int phoneNumber = Integer.parseInt(txtPhoneNumber.getText());
        int chickenQty = (int) chickenBiriyaniQty.getValue();
        int beefQty = (int) beefBiriyaniQty.getValue();
        int muttonQty = (int) muttonBiriyaniQty.getValue();
        int extraChicken = (int) extraChickenQty.getValue();
        int extraWattalapam = (int) extraWattalapamQty.getValue();
        double totalAmount = Double.parseDouble(amoutTotal.getText().replace("$", "")); 
        double advancePayment = Double.parseDouble(txtAdvancePayment.getText().replace("$", "")); 
        double balance = totalAmount - advancePayment;
        
        Order.orderConfirm(customerName, phoneNumber, chickenQty, beefQty, muttonQty, extraChicken, extraWattalapam, totalAmount, advancePayment, balance);
        Order.clearOrder(txtName, txtPhoneNumber, chickenBiriyaniQty, beefBiriyaniQty, muttonBiriyaniQty, extraChickenQty, extraWattalapamQty, chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount, amoutTotal, pendingBalance, txtAdvancePayment);
        
        
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       Order.clearOrder(txtName, txtPhoneNumber, chickenBiriyaniQty, beefBiriyaniQty, muttonBiriyaniQty, extraChickenQty, extraWattalapamQty, chickenBiriyaniAmount, beefBiriyaniAmount, muttonBiriyaniAmount, extraChickenAmount, extraWattalapamAmount, amoutTotal, pendingBalance, txtAdvancePayment);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrder().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amoutTotal;
    private javax.swing.JLabel beefBiriyaniAmount;
    private javax.swing.JSpinner beefBiriyaniQty;
    private javax.swing.JLabel beefBiriyaniUP;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JLabel chickenBiriyaniAmount;
    private javax.swing.JSpinner chickenBiriyaniQty;
    private javax.swing.JLabel chickenBiriyaniUP;
    private javax.swing.JLabel extraChickenAmount;
    private javax.swing.JSpinner extraChickenQty;
    private javax.swing.JLabel extraChickenUP;
    private javax.swing.JLabel extraWattalapamAmount;
    private javax.swing.JSpinner extraWattalapamQty;
    private javax.swing.JLabel extraWattalapamUP;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel muttonBiriyaniAmount;
    private javax.swing.JSpinner muttonBiriyaniQty;
    private javax.swing.JLabel muttonBiriyaniUP;
    private javax.swing.JLabel pendingBalance;
    private javax.swing.JTextField txtAdvancePayment;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
